language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build

elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.1

otp_release:
  - 20.3
  - 21.1
  - 22.0.7

env:
  global:
    - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix compile
  - mix test --trace
  - mix dialyzer --halt-exit-status
  - mix format --check-formatted
  - mix coveralls.travis --trace
  - mix credo --strict

# Leave only .plt files in build
fore_cache:
  - mix deps.clean --all --build
  - mix clean --build

sudo: false
