language: elixir

elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
otp_release:
  - 23.0
  - 22.0
  - 21.0

jobs:
  exclude:
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.7
      otp_release: 23.0

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mix compile
  - MIX_ENV=test mix compile

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix dialyzer
  - mix test
  - mix coveralls.travis --trace

# Leave only .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build
    - priv/plts
